version: '3.8'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
    - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    
  postgres:
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge